export const CONSTANTS = {
    GUTENBERG_BOOK_COUNT: 69369,
    END_OF_BOOK: '*** END OF',
    START_OF_BOOK: '*** START OF',
    LANGUAGE:'\nLanguage:',
    LANGUAGE_OFFSET:11,
    ENGLISH:'English',
    ENGLISH_OFFSET:7,
    NEXT_BOOK:'incompatible',
    EXIT:10,
    GetBookLocation:"GetBookLocation",
    GetBookContent:"GetBookContent",
    ProcessBook:"ProcessBook",
    SummaryByFrequency:"SummaryByFrequency",
    SummaryByRank:"SummaryByRank",
    gutenbergAnalysisUga:"gutenberg-analysis-uga",
    SaveToDrive:"SaveToDrive",
    SaveCloudKey:'SaveCloudKey',
    SentimentAnalysis:'SentimentAnalysis',
}